// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list_contacts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contacts_default = defineTool({
  name: "list_contacts",
  title: "\u5217\u51FA\u806F\u7D61\u4EBA",
  description: "\u5217\u51FA\u76EE\u524D\u767B\u5165\u4F7F\u7528\u8005\u5728 RICH \u7CFB\u7D71\u4E2D\u7684\u806F\u7D61\u4EBA\uFF08\u53EF\u7528 heat \u6216\u95DC\u9375\u5B57\u904E\u6FFE\uFF0C\u9810\u8A2D\u56DE\u50B3\u6700\u8FD1\u66F4\u65B0\u7684 50 \u7B46\uFF09\u3002",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("\u56DE\u50B3\u7B46\u6578\u4E0A\u9650\uFF08\u9810\u8A2D 50\uFF0C\u6700\u591A 200\uFF09"),
    heat: z.enum(["cold", "warm", "hot", "loyal"]).optional().describe("\u4F9D\u71B1\u5EA6\u7BE9\u9078"),
    search: z.string().trim().min(1).optional().describe("\u5728\u59D3\u540D / \u7DBD\u865F / \u6703\u54E1\u7DE8\u865F\u6A21\u7CCA\u641C\u5C0B")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, heat, search }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "\u672A\u767B\u5165" }], isError: true };
    const sb = client(ctx);
    let q = sb.from("contacts").select("id,name,nickname,member_id,heat,region,last_contact_date,updated_at,product_tags,statuses").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (heat) q = q.eq("heat", heat);
    if (search) {
      const s = `%${search}%`;
      q = q.or(`name.ilike.${s},nickname.ilike.${s},member_id.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_contact.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_contact_default = defineTool2({
  name: "get_contact",
  title: "\u53D6\u5F97\u806F\u7D61\u4EBA\u5B8C\u6574\u8CC7\u8A0A",
  description: "\u53D6\u5F97\u6307\u5B9A\u806F\u7D61\u4EBA\u7684\u6240\u6709\u6B04\u4F4D\uFF0C\u542B\u6700\u8FD1 10 \u7B46\u4E92\u52D5\u7D00\u9304\u8207 AI \u6D1E\u5BDF\u3002",
  inputSchema: {
    contact_id: z2.string().uuid().describe("\u806F\u7D61\u4EBA UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contact_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "\u672A\u767B\u5165" }], isError: true };
    const sb = client2(ctx);
    const [contactRes, interactionsRes, insightsRes] = await Promise.all([
      sb.from("contacts").select("*").eq("id", contact_id).is("deleted_at", null).maybeSingle(),
      sb.from("interactions").select("id,date,summary,created_at").eq("contact_id", contact_id).order("date", { ascending: false }).limit(10),
      sb.from("contact_insights").select("summary,tags,next_action,invite_scripts,updated_at").eq("contact_id", contact_id).maybeSingle()
    ]);
    if (contactRes.error) return { content: [{ type: "text", text: contactRes.error.message }], isError: true };
    if (!contactRes.data) return { content: [{ type: "text", text: "\u67E5\u7121\u6B64\u806F\u7D61\u4EBA" }], isError: true };
    const payload = {
      contact: contactRes.data,
      recent_interactions: interactionsRes.data ?? [],
      insight: insightsRes.data ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list_interactions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_interactions_default = defineTool3({
  name: "list_interactions",
  title: "\u5217\u51FA\u4E92\u52D5\u7D00\u9304",
  description: "\u5217\u51FA\u767B\u5165\u4F7F\u7528\u8005\u6700\u8FD1\u7684\u4E92\u52D5\u7D00\u9304\uFF08\u53EF\u6307\u5B9A contact_id \u6216\u65E5\u671F\u7BC4\u570D\uFF09\u3002",
  inputSchema: {
    contact_id: z3.string().uuid().optional().describe("\u53EA\u5217\u51FA\u9019\u4F4D\u806F\u7D61\u4EBA\u7684\u4E92\u52D5"),
    since: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("\u8D77\u59CB\u65E5\u671F YYYY-MM-DD"),
    limit: z3.number().int().min(1).max(200).optional().describe("\u56DE\u50B3\u7B46\u6578\u4E0A\u9650\uFF08\u9810\u8A2D 50\uFF09")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contact_id, since, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "\u672A\u767B\u5165" }], isError: true };
    const sb = client3(ctx);
    let q = sb.from("interactions").select("id,contact_id,date,summary,created_at").order("date", { ascending: false }).limit(limit ?? 50);
    if (contact_id) q = q.eq("contact_id", contact_id);
    if (since) q = q.gte("date", since);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { interactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create_interaction.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_interaction_default = defineTool4({
  name: "create_interaction",
  title: "\u65B0\u589E\u4E92\u52D5\u7D00\u9304",
  description: "\u70BA\u6307\u5B9A\u806F\u7D61\u4EBA\u65B0\u589E\u4E00\u7B46\u4E92\u52D5\u7D00\u9304\u3002",
  inputSchema: {
    contact_id: z4.string().uuid().describe("\u806F\u7D61\u4EBA UUID"),
    summary: z4.string().trim().min(1).describe("\u4E92\u52D5\u5167\u5BB9\u6458\u8981"),
    date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("\u4E92\u52D5\u65E5\u671F YYYY-MM-DD\uFF0C\u9810\u8A2D\u4ECA\u65E5")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ contact_id, summary, date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "\u672A\u767B\u5165" }], isError: true };
    const sb = client4(ctx);
    const payload = {
      contact_id,
      summary,
      user_id: ctx.getUserId()
    };
    if (date) payload.date = date;
    const { data, error } = await sb.from("interactions").insert(payload).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { interaction: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zoyslhfaqxydwkrhaofe";
var mcp_default = defineMcp({
  name: "rich-list-mcp",
  title: "RICH \u7CFB\u7D71\u540D\u55AE\u7BA1\u7406",
  version: "0.1.0",
  instructions: "\u5B58\u53D6 RICH \u7CFB\u7D71\u4E2D\u8A72\u4F7F\u7528\u8005\u7684\u806F\u7D61\u4EBA\u8207\u4E92\u52D5\u7D00\u9304\u3002\u53EF\u7528 list_contacts / get_contact \u67E5\u8A62\uFF0C\u7528 list_interactions \u8FFD\u8E64\u6700\u8FD1\u4E92\u52D5\uFF0C\u7528 create_interaction \u88DC\u8A18\u3002\u6240\u6709\u64CD\u4F5C\u7686\u5728\u8A72\u4F7F\u7528\u8005\u7684\u8CC7\u6599\u7BC4\u570D\u5167\u57F7\u884C\uFF08\u53D7 RLS \u4FDD\u8B77\uFF09\u3002",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_contacts_default, get_contact_default, list_interactions_default, create_interaction_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
